# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MEMECHIN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'Alamofire', '~> 5.2.2'
  pod 'Kingfisher' 
  # Pods for MEMECHIN

end
